-- 1
CREATE OR REPLACE FUNCTION s_nombreEmpleado(codigo INTEGER)
RETURNS VARCHAR AS $$
	SELECT ENAME
	FROM EMP
	WHERE EMPNO = codigo;
$$ LANGUAGE sql;
-- 2
CREATE OR REPLACE FUNCTION s_salEmpleado(codigo INTEGER)
RETURNS NUMERIC AS $$
	SELECT SUM(SAL + COALESCE(COMM, 0))
	FROM EMP
	WHERE EMPNO = codigo;
$$ LANGUAGE sql;
-- 3
CREATE OR REPLACE FUNCTION s_nuevoPedido()
RETURNS INTEGER AS $$
	SELECT (MAX(ORDID) + 1)
	FROM ORD;
$$ LANGUAGE sql;
-- 4
CREATE OR REPLACE FUNCTION s_impTotal(codigo INTEGER)
RETURNS NUMERIC AS $$
	SELECT TOTAL
	FROM ORD
	WHERE ORDID = codigo;
$$ LANGUAGE sql;
-- 5
--  a
CREATE OR REPLACE FUNCTION s_impTotalEmpA(codigo INTEGER, fechaIn DATE, fechaFin DATE)
RETURNS NUMERIC AS $$
	SELECT SUM(O.TOTAL)
	FROM (ORD O 
		JOIN CUSTOMER C ON C.CUSTID = O.CUSTID)
		JOIN EMP E ON E.EMPNO = C.REPID
	WHERE (E.EMPNO = codigo) AND (O.ORDERDATE BETWEEN fechaIn AND fechaFin);
$$ LANGUAGE sql;
--  b
CREATE OR REPLACE FUNCTION s_impTotalEmpB(codigo INTEGER, fechaIn DATE, fechaFin DATE)
RETURNS SETOF RECORD AS $$
	SELECT SUM(O.TOTAL) AS SUMA, E.ENAME
	FROM (ORD O 
		JOIN CUSTOMER C ON C.CUSTID = O.CUSTID)
		JOIN EMP E ON E.EMPNO = C.REPID
	WHERE (E.EMPNO = codigo) AND (O.ORDERDATE BETWEEN fechaIn AND fechaFin)
	GROUP BY E.ENAME;
$$ LANGUAGE sql;
